### ISSUE TITLE
Weetweet Does Not Read From sec.conf

### ISSUE THREAD

**Issue by ibrokemypie** [DarkDefender/weetweet#12]
Setting ${secure.data.*} for the tokens does not work and gets read as unknown...

**Comment by DarkDefender** [comment]
Any tips/hints on how to fix this?

I got the impression that weetweet builtin encryption would automagically just work.
But I guess that it doesn't?

**Comment by ibrokemypie** [comment]
apparently according to some people in the irc channel, you need to evaluate the settings rather than reading it how it is currently, will look for some more detail now

**Comment by DarkDefender** [comment]
Ah, ok. Thanks for looking it up!

I'm quite busy with finals now so I can't promise that I can implement this quickly. (Think that it should be quite strait forward to implement, but I really need to focus on my studies for a few weeks)

However, pull requests are welcome if you want to have a go at it.

**Comment by DarkDefender** [comment]
Can you try out the branch crypt_eval and see if it works for you?

**Comment by ibrokemypie** [comment]
awesome, after re-authing then setting the new token and secret in secure, it is working fine, thank you!

**Comment by DarkDefender** [comment]
Ok nice! :)

Before  pushing the branch upstream, I will also try to rework the start up commands to the twitter stream process. Because right now it has the tokens in the process name in plain text...

However, I have to admit that even when this is fixed, I can't really say that it would be hard to get the plain text tokens if you know what you are doing. But it would require access to your computer (via ssh or real life). So I guess that I can't guard against that anyways, right?

**Comment by ibrokemypie** [comment]
Yep, the main point imo is to have the secure tokens not stored anywhere in plaintext, for me this is so that I can add my weechat configs to my public dotfiles without sharing them. Sure, they still have access to my tokens, but they need my passphrase as well to decrypt them

**Comment by DarkDefender** [comment]
Ok, now I have reworked the stream startup commands and pushed the changes to the branch.

If you don't have any more requests or find any issues, then I intend to push these changes upstream to the weechat script repo by the end of the week.

**Comment by DarkDefender** [comment]
It the updated script should now be available in the official script repo.

Thank you for helping improve weetweet! :)
