### ISSUE TITLE
Been trying to load the script for 2 hours....

### ISSUE THREAD

**Issue by mrFroggy** [DarkDefender/weetweet#15]
python: loading script "weetweet.py"
21:46:35  weechat     | You need to have pkg_resources installed for version checking
21:46:35  weechat     | python: registered script "weetweet", version 1.2.6 (Weechat twitter client)
21:46:35  weechat     | Can't load twitter python lib >= 1.14.1
21:46:35  weechat     | Install it via your package manager or go to http://mike.verdone.ca/twitter/
i have the libs install with pip3 any input is welcome

**Comment by DarkDefender** [comment]
Does weechat run in python3 mode?

I'm guessing it isn't. If weechat runs in python2 mode, you need to install the libs for python2. So you need to install them with `pip2` also.

Let me know of it goes.

**Comment by mrFroggy** [comment]
Yepp that was my misstake doh!

**Comment by DarkDefender** [comment]
Can this issue be closed now? Do you have any more problems/questions?

**Comment by mrFroggy** [comment]
Sorry forgot closed now thanks!
