### ISSUE TITLE
Keep trying to reconnect

### ISSUE THREAD

**Issue by varac** [DarkDefender/weetweet#16]
Please let weetweet constantly try to reconnect after disconnection, so no manual intervention is needed.

```
Nov 17 21:02:32 ℹ  recv stream data: Disconnected, trying to reconnect.
Nov 17 21:02:38 ℹ  recv stream data: Disconnected, trying to reconnect.
Nov 17 21:02:38 ℹ  Stream shut down after: Hangup. You'll have to restart
the stream manually. (:re_home, if home stream)
```

**Comment by DarkDefender** [comment]
I know it's annoying and I've also been bother by it quite a bit lately. However, I think I implemented it that way to avoid bans. If I recall correctly, then twitter will ban you if you try to spam reconnects.

I think we can perhaps side step this if we instead greadually increase the timer. Right now it tries a few times during a 10 second windows to reconnect. If it fails after that it gives up.

Do you think that have a delay sequence like this is ok: 1sec, 5sec, 10sec, 1min, 2min
And then try to reconnect every 2 minutes.

Do you feel like this would be a nice solution?

**Comment by varac** [comment]
@DarkDefender Perfect !

**Comment by DarkDefender** [comment]
I've pushed some changes that should fix this to master branch. Because it's hard to test this (you can not trigger hangups or other error that could happen) it would be really nice if you could try it out and see how it goes.

**Comment by varac** [comment]
@DarkDefender thx, I am using latest master now and let you know if it works on next disconnect!

**Comment by DarkDefender** [comment]
It has worked fine for me so far so I'll close this one now as there doesn't seem to be any obvious issues
