### ISSUE TITLE
Stream broken with weechat 2.0

### ISSUE THREAD

**Issue by DarkDefender** [DarkDefender/weetweet#17]
The twitter stream is currently broken because weechat accidentally broke some python API stuff. Hopefully this will be fixed soon and we'll get a new stable release.

**Comment by jpmenil** [comment]
Hi,
i can confirm :)

I temporarily fix it like that for now:
╭─jean-philippe@grosjean /tmp  
╰─➤ diff weetweet.py ~/.weechat/python/weetweet.py                                                                                                         1 ↵
354c354
<     server = sock_fd_dict[sock_fd_dict[fd]]
---
>     server = sock_fd_dict[sock_fd_dict['file_fd']]
381c381
<                 name = sock_fd_dict[fd],
---
>                 name = sock_fd_dict['file_fd'],
578c578
<         sock_fd_dict[str(file_fd)] = name
---
>         sock_fd_dict['file_fd'] = name

Regards.

**Comment by DarkDefender** [comment]
The API breakage is fixed with: https://github.com/weechat/weechat/commit/515334e53b431c353ce3c407f58b880fbf749fc3

However, I still need to update the code for the API change where they now send fd as an int instead of a string. But I have still not gotten and answer if 2.0.1 will come soon or not...

**Comment by jpmenil** [comment]
Good catch !

**Comment by DarkDefender** [comment]
I've added a temporary fix for weechat 2.0. If 2.0.1 is not released by then end of the week. I'll push this change upstream

**Comment by jpmenil** [comment]
Nice.
Look better thant my workaround :)

Thanks !

**Comment by DarkDefender** [comment]
This is now fixed upstream
