### ISSUE TITLE
Problems with auth

### ISSUE THREAD

**Issue by slackhead** [DarkDefender/weetweet#21]
This is going to sound silly, but I've just had to install weechat + twitter + weetweet on my laptop after my server HDD crashed, but I've totally forgotten how to :auth. Should I supply username/email + pass?

I'm not seeing anything return in the buffer whatever I try.  In oauth_proc_cb() weechat.prnt("", out) returns empty although data is 'auth1'.

**Comment by DarkDefender** [comment]
It seems like it is broken currently. I guess that twitter might have removed the auth method that I use. I get 404 error when I try to create a new auth.

The idea is that you type :auth , get a link to a webpage where you will get a pin and then type :auth <pin>

But it seems like this is not working atm.

**Comment by DarkDefender** [comment]
Fixed it.
Good that you found it. But it was your change that broke it (I should have tested it too...):
https://github.com/DarkDefender/weetweet/commit/0382833c4a5da64f5271daacbbe33312c5082ac6#diff-eb1735a0495054e153fbc70c793ccbb1R747

It works if I revert that. I've pushed the change to master.
