### ISSUE TITLE
Can't load twitter lib

### ISSUE THREAD

**Issue by OrdinaryMagician** [DarkDefender/weetweet#6]
<pre>
You need the have pkg_resources installed for version checking
Can't load twitter python lib >= 1.14.1
</pre>

<pre>
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/marisa/.weechat/python/autoload/weetweet.py", line 1000, in oauth_proc_cb
python: stdout/stderr:     process_output = ast.literal_eval(out)
python: stdout/stderr:   File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
python: stdout/stderr:     node_or_string = parse(node_or_string, mode='eval')
python: stdout/stderr:   File "/usr/lib/python2.7/ast.py", line 37, in parse
python: stdout/stderr:     return compile(source, filename, mode, PyCF_ONLY_AST)
python: stdout/stderr:   File "<unknown>", line 1
python: stdout/stderr:     You need the have pkg_resources installed for version checking
python: stdout/stderr:            ^
python: stdout/stderr: SyntaxError: invalid syntax
python: error in function "oauth_proc_cb"
</pre>

So this came up out of nowhere after I did a system upgrade this morning. I don't know what exactly is going on.

I do have python twitter tools 1.14.1 installed, though.

**Comment by MatthewCox** [comment]
@OrdinaryMagician what did you mean by 'rebuild everything'? I'm having the same issue, and reinstalling the libraries involved doesn't seem to be working.

**Comment by MatthewCox** [comment]
Nevermind, also solved it.

For future reference, I needed to install the python3 version of pip (via `sudo -H python3 get-pip.py`), then `sudo -H pip3 install twitter`
