### ISSUE TITLE
Adding a favorite prints huge amount of JSON instead of just the tweet

### ISSUE THREAD

**Issue by BlitzKraft** [DarkDefender/weetweet#9]
This is what I get when I favorite a tweet through the twitter script in weechat. 

`You fave'd the following tweet:                                                                                                                                                                     
recv stream data: {'source': {'follow_request_sent': None, 'profile_use_background_image': True, 'profile_background_image_url_https': None, 'description': None, 'verified': False,                
'profile_image_url_https': 'https://pbs.twimg.com/profile_images/732784770795495424/spFEFxBL_normal.jpg', 'profile_sidebar_fill_color': 'DDEEF6', 'id': 732781656612950016, 'profile_text_color':   
'333333', 'followers_count': 10, 'profile_sidebar_border_color': 'C0DEED', 'location': None, 'profile_background_color': 'F5F8FA', 'id_str': '732781656612950016', 'is_translation_enabled': False, 
'utc_offset': None, 'statuses_count': 4, 'default_profile_image': False, 'friends_count': 18, 'profile_link_color': '2B7BB9', 'profile_image_url':                                                  
'http://pbs.twimg.com/profile_images/732784770795495424/spFEFxBL_normal.jpg', 'notifications': None, 'geo_enabled': False, 'profile_background_image_url': None, 'name': 'Bharath kishore', 'lang': 
'en', 'following': None, 'profile_background_tile': False, 'favourites_count': 3, 'screen_name': 'OneTrueBK', 'url': 'http://blitzkraft.me', 'created_at': 'Wed May 18 03:55:36 +0000 2016',        
'contributors_enabled': False, 'time_zone': None, 'protected': False, 'default_profile': True, 'is_translator': False, 'listed_count': 0}, 'created_at': 'Mon Jun 06 06:07:22 +0000 2016', 'event': 
'favorite', 'target_object': {'contributors': None, 'truncated': False, 'text': 'Fuck off Travis.', 'is_quote_status': False, 'in_reply_to_status_id': None, 'id': 739688109860786181,              
'favorite_count': 3, 'source': '<a href="http://twitter.com/gitlost" rel="nofollow">Profane Commits</a>', 'retweeted': False, 'coordinates': None, 'entities': {'symbols': [], 'user_mentions': [], 
'hashtags': [], 'urls': []}, 'in_reply_to_screen_name': None, 'in_reply_to_user_id': None, 'retweet_count': 0, 'id_str': '739688109860786181', 'favorited': False, 'user': {'follow_request_sent':  
None, 'profile_use_background_image': True, 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'description': 'Github commit messages containing profanity. 
Picture is of a burning NeXT Cube. Developed by @uiri00', 'verified': False, 'profile_image_url_https':                                                                                             
'https://pbs.twimg.com/profile_images/3336578378/a60d4b744784d4ab05ee1846234e0708_normal.jpeg', 'profile_sidebar_fill_color': 'DDEEF6', 'id': 1240421984, 'profile_text_color': '333333',           
'followers_count': 1991, 'profile_sidebar_border_color': 'C0DEED', 'location': None, 'profile_background_color': 'C0DEED', 'id_str': '1240421984', 'is_translation_enabled': False, 'utc_offset':   
None, 'statuses_count': 31059, 'default_profile_image': False, 'friends_count': 5, 'profile_link_color': '0084B4', 'profile_image_url':                                                             
'http://pbs.twimg.com/profile_images/3336578378/a60d4b744784d4ab05ee1846234e0708_normal.jpeg', 'notifications': None, 'geo_enabled': False, 'profile_background_image_url':                         
'http://abs.twimg.com/images/themes/theme1/bg.png', 'name': 'Developers Swearing', 'lang': 'en', 'following': None, 'profile_background_tile': False, 'favourites_count': 0, 'screen_name':         
'gitlost', 'url': None, 'created_at': 'Mon Mar 04 03:44:49 +0000 2013', 'contributors_enabled': False, 'time_zone': None, 'protected': False, 'default_profile': True, 'is_translator': False,      
'listed_count': 85}, 'geo': None, 'in_reply_to_user_id_str': None, 'lang': 'en', 'created_at': 'Mon Jun 06 05:19:22 +0000 2016', 'in_reply_to_status_id_str': None, 'place': None}, 'target':       
{'follow_request_sent': None, 'profile_use_background_image': True, 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'description': 'Github commit        
messages containing profanity. Picture is of a burning NeXT Cube. Developed by @uiri00', 'verified': False, 'profile_image_url_https':                                                              
'https://pbs.twimg.com/profile_images/3336578378/a60d4b744784d4ab05ee1846234e0708_normal.jpeg', 'profile_sidebar_fill_color': 'DDEEF6', 'id': 1240421984, 'profile_text_color': '333333',           
'followers_count': 1991, 'profile_sidebar_border_color': 'C0DEED', 'location': None, 'profile_background_color': 'C0DEED', 'id_str': '1240421984', 'is_translation_enabled': False, 'utc_offset':   
None, 'statuses_count': 31059, 'default_profile_image': False, 'friends_count': 5, 'profile_link_color': '0084B4', 'profile_image_url':                                                             
'http://pbs.twimg.com/profile_images/3336578378/a60d4b744784d4ab05ee1846234e0708_normal.jpeg', 'notifications': None, 'geo_enabled': False, 'profile_background_image_url':                         
'http://abs.twimg.com/images/themes/theme1/bg.png', 'name': 'Developers Swearing', 'lang': 'en', 'following': None, 'profile_background_tile': False, 'favourites_count': 0, 'screen_name':         
'gitlost', 'url': None, 'created_at': 'Mon Mar 04 03:44:49 +0000 2013', 'contributors_enabled': False, 'time_zone': None, 'protected': False, 'default_profile': True, 'is_translator': False,      
'listed_count': 85}}    `

The tweet exists in the json dict, directly. I am not sure if this is the expected behaviour. 

EDIT: The same also happens when I favorite a tweet on the web while weetweet is running.

**Comment by DarkDefender** [comment]
I can't reproduce this problem...
Are you using the latest version of weetweet? If you have the latest version available via the weechat repo, can you try to use the github version hosted here?

My guess is that you are using a version of weetweet were I printed all the stream messages sent by the twitter stream server. However I should have disabled that quite some time ago.

That also explains why you are getting these messages when using the twitter web interface. It will send certain event to your weetweet twitter stream.

**Comment by BlitzKraft** [comment]
You are correct. I am using the one from weechat repo. Switched to the one here and it is clean.

If I try to favorite a tweet that I already fav'd, it still prints excessive JSON; 

`Unexpected error in get_twitter_data:(<class 'twitter.api.TwitterHTTPError'>,     
TwitterHTTPError("Twitter sent status 403 for URL: 1.1/favorites/create.json using
parameters: (id=739580435210993664&oauth_consumer_key=NVkYe8DAeaw6YRcjw662ZQ&oauth
_nonce=224607746970509005&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1465215
291&oauth_token=732781656612950016-3aUgO9rcBxw7364epsoj2WWahv8vB6X&oauth_version=1
.0&oauth_signature=z%2B81D1JoSmFcQW0vyJRokhykQI4%3D)\ndetails: {'errors':         
[{'message': 'You have already favorited this status.', 'code': 139}]}",),        
<traceback object at 0x7f5a189df148>)                                             
 Call: fav                                                                        
`

**Comment by DarkDefender** [comment]
I guess I'll forgot to push the latest changes to the weechat plugin repo.

I'll try to fix the error message and then push the changes to weechat. However I'm quite busy now so it might take a while.

Patches are welcome! :)

**Comment by DarkDefender** [comment]
Should be fixed now. Can you test it out on your side so I didn't break anything? :P

**Comment by BlitzKraft** [comment]
Thank you very much!! This is fixed.
